# Generated by Django 3.2.12 on 2023-03-16 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_data_hub_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='address',
            field=models.IntegerField(default=8),
        ),
    ]
