# Generated by Django 3.2.12 on 2023-03-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20230316_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='hub',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
