# Generated by Django 4.1.7 on 2023-03-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20230316_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey><django.db.models.fields.IntegerField>', max_length=200),
        ),
    ]
