# Generated by Django 4.1.7 on 2023-03-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hub',
            name='address',
            field=models.CharField(default='0.0.0.0', max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
