# Generated by Django 3.2.12 on 2023-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_data_pub_date_alter_hub_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
