# Generated by Django 4.1.7 on 2023-05-02 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(default='0.0.0.0', max_length=200)),
                ('port', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.IntegerField(default=8)),
                ('location', models.CharField(max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_sensor_nodes.hub')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('pub_date', models.DateTimeField(unique=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_sensor_nodes.node')),
            ],
        ),
    ]
